print("Hello git")
print("Qué tal el curso?")
print("nuevo print")
print("Este es un nuevo cambio GUS")
print("Esto es solo para main")
print("Cambio que no haré commit")
print("Conecté el proyecto a GITHUB")
print("Modificación desde el clón")
